### ISSUE TITLE
Card features unable to save

### ISSUE THREAD

**Issue by kt-wawro** [pathfindertools/microgen#46]
While working on the Launchpad website. the photo cards feature will not save. This happens both when a picture is inserted and if you do not add a picture but just add text. 
<img width="1728" alt="Screen Shot 2022-05-09 at 11 34 56 AM" src="https://user-images.githubusercontent.com/102541949/167446152-c80a1907-6e12-41a3-8e6e-1e7f15d0e016.png">

Site: https://pl-launchpad.vercel.app/admin#/collections/pages

Repo for the site:[ ](https://github.com/pathfindertools/pl-launchpad)

**Comment by tbenbow** [comment]
Fixed, this is in the .3 branch
